### ISSUE TITLE
default is not a constructor (with Babel): Error in docs

### ISSUE THREAD

**Issue by thomasedwards** [pusher/chatkit-server-node#12]
Just been trying this out today. From the examples, I was using this:

```javascript
const chatkit = new Chatkit.default({
  instanceLocator: 'v1:us1:example',
  key: 'your:key'
});
```

However, this returns an error:

```javascript
default is not a constructor
```

I’m using Babel, so my actual error is:

```javascript
_pusherChatkitServer2.default.default is not a constructor
```

I changed my code to this (removing the `.default`):

```javascript
const chatkit = new Chatkit({
  instanceLocator: 'v1:us1:example',
  key: 'your:key'
})
```

And it worked without error.

**Comment by SethuSenthil** [comment]
I'm not using Babel and I'm getting this error too

**Comment by lukejacksonn** [comment]
Hey 👋 I just had a look at this myself. Copying from the docs:

```js
const Chatkit = require('@pusher/chatkit-server')

const chatkit = new Chatkit.default({
  instanceLocator: "v1:us1-staging:...",
  key: "9f0ae37c-1310-4fb2-b517...",
})
```

Which works on node `v8.5.0` without any bundler or babel transforms (like webpack, rollup).

If you are using a bundler and the `import Chatkit from '@pusher/chatkit-server'` syntax then you should be able to omit the `default` property which means that this should work:

```js
import Chatkit from '@pusher/chatkit-server'

const chatkit = new Chatkit({
  instanceLocator: "v1:us1-staging:...",
  key: "9f0ae37c-1310-4fb2-b517...",
})
```

If the above suggestions do not help then could you please provide us with some more details of your setup (versions of node, chatkit-server and babel etc.) as well as your import code and any reproduction steps that might allow us to investigate further!

**Comment by dcsan** [comment]
I noticed an ESLint error that 'constructor should not start with lowercase' wonder if there is a transformation going on somewhere.
