### ISSUE TITLE
Large file size

### ISSUE THREAD

**Issue by thomasedwards** [pusher/chatkit-server-node#17]
My apologies this is such a vague issue, and will be difficult to ‘resolve’, but would love to have a discussion about it.

I’m using Lambda functions to run the services for our app. We have an authorised route into the Lambda functions, and then they connect to ChatKit using this package as a Node.js app.

You probably already know, but in Lambda you have to upload 1 file with everything you need in it. So ideally, you want the file to be as lightweight as possible as you’re billed for usage.

I have an endpoint that creates a type of user in our app, and then once that’s confirmed, they are then also created on ChatKit. All the code I need for my user creation brings to the whole file up to 13.9 kB. (I appreciate that this is a very circumstantial place to be, but as an example), however when I add ChatKit (`pusher-chatkit-server`), this flies up to 2.18 MB.

Having looked through the dependancies, I think it could possibly be including `typescript`, which I know is quite large. I haven’t yet played around with switching to a production build as I know that’s only a dev dependancy.

My ‘issue’, per se, is that I’d love for the file size to be kept clean and simple. At the moment, I’m only using the `createUser` and `authenticate` functions, so it’s tempting for me to write my own functions for these two to shave off a few MB. As more people switch to more recent versions of Node, there’s less need for things like Babel and helpers to get around JavaScript’s lack of, well, lots of things.

As an aside, really loving ChatKit. It’s working really well for us and I’m excited to see where it goes.

**Comment by hamchapman** [comment]
Hey @thomasedwards sorry for the delay in getting back to you! I'm super excited to hear about someone using Chatkit stuff in Lambda! 

Now to actually help with the issue. How are you bundling the JS into a single file that's then uploadable to Lambda? 2.18MB does sound like it's including a _lot_ of dependencies, or a lot of something!

**Comment by thomasedwards** [comment]
Thanks @hamchapman! We‘re using [Netlify](https://www.netlify.com/) [Functions](https://www.netlify.com/docs/functions/). It bundles the file up using Webpack and Babel to make it ready for Node 8.10. Netlify handle all the API Gateway-type work, and it uploads it to Lambda as part of the deployment process. They have a [Node module](https://github.com/netlify/netlify-lambda) you can run locally to test it out with. Our project is private unfortunately, but I can probably put an example together to show you how it’s working for us.

**Comment by thomasedwards** [comment]
(Also, we’re in Farringdon, so we can always just show you if you wanted to see 😄)

**Comment by hamchapman** [comment]
If you're able to get an example together that would be amazing. Otherwise I can try and recreate something myself soon!

**Comment by hamchapman** [comment]
Better late than never, but we've just published 1.0.2 which should significantly reduce the size of the SDK thanks to lots of cleanup in this SDK and pusher-platform-node (a dependency).

Let me know if you get a chance to try it out again and if it makes a difference 👍

**Comment by hamchapman** [comment]
Ah no worries! Thanks for letting me know. I'll close this for now as I think it should be much more reasonable now
