### ISSUE TITLE
setting avatarURL on createUser does not seem to work

### ISSUE THREAD

**Issue by nbransby** [pusher/chatkit-server-node#20]
no avatar is returned when getting the users or shown on the chatkit instance inspector

**Comment by hamchapman** [comment]
I just tested with the latest version and creating a user with an `avatarURL` property does successfully set the property. It is also then returned as part of the response when calling `getUsersByIds` when you provide the ID of the created user who had an `avatarURL` set.

The `avatarURL` not being shown in the inspect is something that we could potentially add, but is not related to this SDK - thanks for the feedback!

Which version of the SDK are you using?

**Comment by nbransby** [comment]
ah yes, i just tried it myself and it works too. I assumed in was the server end as wasnt appearing on the instance inspector but it would appear to be the client end - avatarURL comes back as null from com.pusher:chatkit-core:0.2.4 (android)

**Comment by hamchapman** [comment]
Ah okay, that does seem to be a bug with the Android SDK. I've created an item for us to fix it so look out for a new release of the Android SDK relatively soon. Thanks for the report!
