### ISSUE TITLE
Getting 401 error while authenticating

### ISSUE THREAD

**Issue by vivek1395068** [pusher/chatkit-server-node#31]
const chatManager= new Chatkit.ChatManager({
instanceLocator:"v1:us1:xyz",
userId:"HK",
tokenProvider:new Chatkit.TokenProvider({
url:"http://localhost:8081/authenticate"
})
});
chatManager.connect().then((currentUser)=>{
console.log("current User",currentUser)})
.catch((error)=>{
console.error(error)})

while running the above code from the client

to the node/express server:-
app.post("/authenticate",(req,res)=>{
const {grant_type}=req.body;
res.json(chatkit.authenticate({grant_type,userId:req.query.user_id}));
});

throws an error:-

Logger.ERROR: error establishing presence subscription:
Could not parse the token. More information can be found at https://docs.pusher.com/errors/authentication/jwt/invalid. Error object:
{…}
headers: Object { "Request-Method": "SUBSCRIBE" }
info: {…}
error: "authentication/jwt/invalid"
error_description: "Could not parse the token"
error_uri: "https://docs.pusher.com/errors/authentication/jwt/invalid"
proto: Object { … }
statusCode: 401
proto: Object { … }

Can someone help me out fixing the 
![error chatkit](https://user-images.githubusercontent.com/22879580/49282725-e307d780-f4b5-11e8-96fb-6adaf9243492.PNG)
error.
Note:- I provided the correct "instanceLocator" in my application (not the one mentioned above)

**Comment by hamchapman** [comment]
What version of the SDK are you using?

Also your `authenticate` code should look more like this: https://github.com/pusher/chatkit-server-node/blob/1b2c07cd3de434bd6ad451a7dc8798cacf917a69/examples/auth_server.js#L12-L20

Obviously you'll want to use your `req.query.user_id` in there

**Comment by vivek1395068** [comment]
Thanks, that resolved the issue. Probably i was using an older version of code, that was creating the issue.

Thank you so much !!!!
