### ISSUE TITLE
Enhancement Request: send notifications from Node JS via Chatkit to existing user

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-server-node#34]
### What?

We would like to send a notification to existing chatkit users of our app when they are invited to a new room using the Chatkit notification UI. We'd like these only to be sent if the user receiving the notification's app is not currently open and in the foreground on iOS or Android (just as is currently done with the room messages). We use channels to pop up an invitation dialog if the app is running in the foreground.

Currently we are tryin g using Beams but it does not seem to be compatible with Chatkit push notifications so we've had to turn Beams off and currently cannot send invitations in the form of push notifications.

**Comment by hamchapman** [comment]
@hitchingsh currently you can't use Beams "manually" alongside Chatkit (if you're using Chatkit's push notifications). This is a restriction that we'll be looking to lift in the future.

For now, your best option would likely be to create a private room for each user that only they are a member of. You can then hide this room from users in your app's UI and use it just for your server to send messages to which would then show up as push notifications for the user if they're not connected to Chatkit.

**Comment by hitchingsh** [comment]
Of my three Node JS server requests filed so far, this is the lowest priority and currently we do not have a blocking dependency on this.

**Comment by callum-oakley** [comment]
Over the course of the last year, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.
