### ISSUE TITLE
Chatkit Node JS updateUser does not propagate changes to Swift & Android clients

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-server-node#35]
### What?

In node JS we update the user's name or avatarURL as shown below but those changes are not propagated to the rooms and users in the rooms of that user. 

  var updateUserArgs = {
    id: userId,
    name: name,
    avatarURL: avatarURL,
  }

  await chatkit.updateUser(updateUserArgs)
  .then(() => {
    console.log('User " + userId + " updated successfully');
  }).catch((err) => {
    console.log(err);
    reportError("/updateUser failed because invalid userId " + userId)
  })

### Suggested improvements

 We'd like to be able to update the user's avatarURL and name updated for all users connected to all rooms with that user in it and also have that their user info updated for anyone receiving messages from them.

**Comment by hamchapman** [comment]
This is a feature that we'll be adding in the future 👍

**Comment by callum-oakley** [comment]
Over the course of the last year, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.
