### ISSUE TITLE
Add ability to turn notifications on and off on a specific room from Node JS server

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-server-node#36]
### What?

Add the ability to turn automatic sending of notifications for a room.  

### Suggested improvements

Thus when turned off, when a sendMessage is called either from the client or server it won't send a notification. We need this for a specific use case for our application and have gone to significant lengths to work around this limitation.  

This could also be implemented as an option to sendMessage

**Comment by hitchingsh** [comment]
The use case is we want to allow everyone to type an answer in chat to a question before anyone else sees the answer

**Comment by callum-oakley** [comment]
Over the course of the last year, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.
