### ISSUE TITLE
Need ability to sendMessage with attachment link from Node JS

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-server-node#37]
### What?

Need ability to sendMessage with attachment link from Node JS

### Suggested improvements

Extend sendMessage in NodeJS to allowing including attachment URL that points to an image on another web server.  We need this for our application.

**Comment by callum-oakley** [comment]
@hitchingsh sending messages with attachments [is actually supported](https://github.com/pusher/chatkit-server-node/blob/master/tests/main.ts#L518-L527) in version 1.x. Though you have made me realise it isn't documented... we'll get that fixed up ASAP. Closing this on the assumption that the sendMessage method works as you need it to, but feel free to re-open if you run in to any issues with it!

**Comment by hitchingsh** [comment]
With the help of the support slack channel I was able to figure this out.  Please do add it to the documentation

    chatkit.sendMessage({
      userId: msg.msgUserId,
      roomId: roomId,
      text: msg.msgText,
      attachment: {
        resourceLink: msg.msgImageURL,
        type: "image",
      }
    })
