### ISSUE TITLE
how to subscribe to a USERS messages (not a rooms)

### ISSUE THREAD

**Issue by dcsan** [pusher/chatkit-server-node#41]
### What?
since there's a higher level API here, it would be nice to get all messages for a user across multiple rooms, not have to subscribe to multiple rooms. Is there a way to do this?

### Suggested improvements
it looks like messages are only sent in response to room sub events
https://docs.pusher.com/chatkit/reference/subscription-events#new-message

**Comment by callum-oakley** [comment]
Over the course of the last year, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.
