### ISSUE TITLE
chatkit.getUsersByID is not a function

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-server-node#47]
### What?
I'm trying to get the individual user's data after a call to `chatkit.getRoom`. From that call I get the `member_user_ids` which I then supply as an argument to the `chatkit.getUsersByID` method. 

Even supplying the user IDs directly (as the [docs](https://docs.pusher.com/chatkit/reference/server-node#get-users-by-id) suggest) doesn't seem to work:

```
 const members = await chatkit.getUsersByID({
  userIds: [
    "193419644",
    "2087566530",
    "2087898568"
  ]
});
```

I'm using version `1.1.0` of `@pusher/chatkit-server`.

**Comment by anchetaWern** [comment]
This was a simple typo in the documentation. `chatkit.getUsersById` (small letter `d`) works. Closing this now, but documentation should be updated.

**Comment by callum-oakley** [comment]
Sorry about this, and thanks for following up! Will get that typo corrected asap.
