### ISSUE TITLE
Slight error in the docs for deleting a message

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-server-node#57]
### What?

Slight error in the docs for deleting a message: https://pusher.com/docs/chatkit/reference/server-node#delete-a-message

### Suggested improvements

It should be `id` instead of `messageId`:

```
chatkit.deleteMessage({
  roomId: roomToDeleteMessageFrom.id
  id: messageToDelete.id
})
```

**Comment by jonathanlloyd** [comment]
Thanks for letting us know :raised_hands: ! Should be fixed now.
